/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A career expressed as timestamped entities with lifecycles, for rendering as an explorable city. The consumer of this contract does not know or care whose career it is: it reads dates and decides what exists, what is under construction, and what has been upgraded at any point on a timeline. Chronicle is one producer of this shape; any system that can emit it can drive the same renderer.
 */
export interface CareerGraphV1 {
  /**
   * Contract major version. A consumer must refuse a version it does not understand rather than guess.
   */
  version: 1;
  /**
   * When this document was produced. Not when anything in it happened.
   */
  generatedAt: string;
  /**
   * Whose career this is. Presentation only - the renderer never branches on it.
   */
  subject: {
    name: string;
    headline?: string | null;
    url?: string | null;
  };
  /**
   * Everything in the city. Flat rather than nested, because an entity's place in the world is decided by its own dates and district, not by where it sits in a document.
   */
  entities: Entity[];
}
export interface Entity {
  /**
   * Stable across regenerations. A consumer animating between two documents relies on this to know that a building moved rather than that one vanished and another appeared.
   */
  id: string;
  /**
   * What this becomes in the world. building = a capability that grows in place; road = work that connects capabilities; district = a grouping; landmark = a moment that happened once.
   */
  kind: "building" | "road" | "district" | "landmark";
  label: string;
  /**
   * The id of the district this belongs to, or null for entities that stand alone.
   */
  district?: string | null;
  /**
   * When this came into existence. Before this date the renderer must not show it at all - that is the entire premise of the timeline.
   */
  built: string;
  /**
   * Dates on which this grew. A capability deepening is an upgrade in place, never a replacement, so a building gains storeys rather than being demolished and rebuilt.
   */
  upgraded?: string[];
  /**
   * When this stopped being current, if it ever did. Not a deletion: the renderer may show it unlit or weathered rather than removing it, because it did happen.
   */
  retired?: string | null;
  /**
   * Relative size, 0 to 1, normalised by the producer. Height for a building, width for a road. Normalised rather than raw because only the producer knows what the maximum means - years of experience, lines of code, or something else entirely.
   */
  magnitude?: number;
  /**
   * For roads: the entity ids this links. A project connects the capabilities it used, which is what makes it visually obvious how the pieces worked together.
   */
  connects?: string[];
  /**
   * True for anything stated as an intention rather than a fact. The renderer MUST make these unmistakably different from built entities - blueprints, scaffolding, holograms. This flag is what lets the city be ambitious without being dishonest.
   */
  speculative?: boolean;
  /**
   * Where to read more, if anywhere. Absolute.
   */
  href?: string | null;
  /**
   * Producer-specific extras. A consumer must ignore anything here it does not recognise, so a producer can add detail without breaking every renderer.
   */
  meta?: {
    [k: string]: unknown;
  };
}
